name: Kalkulator_Sawit
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^0.35.0
  intl: ^0.20.2
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icc.png"

flutter:
  uses-material-design: true

  # Tambahkan folder assets untuk gambar logo
  assets:
    - assets/images/bg.jpg
    - assets/images/LOGO-ITSI1.PNG

  # Tambahkan font custom jika diperlukan
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
